### PR TITLE
Issue #1 Resolution

### PR DESCRIPTION
**Pull request by cleverington**
Fully prepared and organized for GitBook.

Showcase Example: https://cleverington.gitbooks.io/drupal-organizer-resources/content/

(Will drop the Showcase once we can get the 'real' book online.)

### CODE REVIEW

**Comment by drnikki** [comment]
👍 💯 I am on board with this! I've submitted a request to gitbook to give us a free organization account since we're an open source community organization.  If that doesn't work, can we push gitbooks to gh pages or are they incompatible?

**Comment by cleverington** [comment]
Perfect!

That was precisely what I was wanting to touch base with you on.

Once they give you the Organization, send an invite to me for the Org and I will publish the GitBook through the org and pull down the showcase.

As for gitpages, the two are not mutually exclusive. I will need to 'play' a little in the docroot to make it load properly in both, I believe.  Might have to wait for the turn of the year when I can get a personal-use unix shell and Ruby/Gems/Jekyll though. 

There are a few items that I do not _believe_ work between the two (such as `for` loops and JSON variables), but I am 90% certain that can be addressed via Plugins.  So no worries.

Cheers!

**Comment by cleverington** [comment]
@drnikki Do you want me to go ahead and complete the PL so Contributors can see the 'new' look of the documents?

**Comment by drnikki** [comment]
@cleverington yes, I'll merge this in.  Until (if) we can get a free gitbook account, it might be best to focus on ghpages/jekyll so that we can move forward.

**Pull request merged**
